import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Learning next JS",
  description: "Generated by Cristian Villamizar",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-900 min-h-screen`}
      >
        {/*Header*/}
        <header className="bg-white shadow p-4 flex justify-center gap-6">
          <a href="/" className="text-blue-600 font-medium hover:undeline">
            Inicio
          </a>
          <a href="/about" className="text-blue-600 font-medium hover:underline">
            Acerca
          </a>
          <a href="/contact" className="text-blue-600 font-medium hover:underline" >
            Contacto
          </a>
        </header>

        {/*Contenido dimanico*/}
        <main className="p-10">
          {children}
        </main>

        {/*Footer*/}
        <footer className="text-center p-4 text-sm text-gray-500 border-t">
          © {new Date().getFullYear()} Mi app Next.js
        </footer>        
      </body>
    </html>
  );
}
